project: 
  name: PBC Classification Project
  
data:
  data_dir: './data'
  dataset_folder: "PBC_dataset_normal_DIB_224/PBC_dataset_normal_DIB_224"
  
class_names:
  - basophil
  - eosinophil
  - erythroblast
  - ig
  - lymphocyte
  - monocyte
  - neutrophil
  - platelet

model:
  name: vit_base_patch16_224
  num_classes: 8

loss:
  name: CrossEntropyLoss

experiment:
  name: PBC Classification
  num_epochs: 100
  patience: 20
  image_size: 224
  batch_size: 8
  learning_rate: 0.001
  split_ratio: 0.2
  num_workers: 8
  accelerator: cpu  # cpu, cuda, or mps
  devices: auto
  random_seed: 42
  
use_scheduler: True
use_checkpointing: True
log_artifacts: True

